### PR TITLE
Fix type instability in closure emitted by `flatten`  for `Vector`

### LINKED ISSUE #60: Why constructor instead of `identity`
I was wondering why a constructor is used for the unflatten function in 

https://github.com/JuliaGaussianProcesses/ParameterHandling.jl/blob/e5e03d1b7bdfffc5d9dbc119fa2f967599071d99/src/flatten.jl#L34

instead of simply the `identity`.

Context: I was chasing an Enzyme error. The following doesn't work:
```julia
using Enzyme, ParameterHandling
testfun(θ) = sum(θ[1])
θ = (rand(10),)
x, unpack = value_flatten(θ)
dx = zero(x)
autodiff(Reverse, testfun ∘ unpack, Duplicated(x, dx)) # ERROR: Duplicated Returns not yet handled
```
But when overloading `flatten` for vectors as follows, it works ok.

```julia
ParameterHandling.flatten(::Type{T}, x::Vector{R}) where {T<:Real,R<:Real} = (Vector{T}(x), identity)
```
There's probably a bug somewhere in Enzyme which makes it so it can't differentiate this,, but as always I find it pretty hard to reduce to a MWE.

### PR DESCRIPTION
**Pull request by simsurace**
Fixes #60

### CODE REVIEW

File: src/flatten.jl [hunk 1]
```diff
@@ -31,7 +31,12 @@ function flatten(::Type{T}, x::R) where {T<:Real,R<:Real}
     return v, unflatten_to_Real
 end
 
-flatten(::Type{T}, x::Vector{R}) where {T<:Real,R<:Real} = (Vector{T}(x), Vector{R})
+function flatten(::Type{T}, x::Vector{R}) where {T<:Real,R<:Real}
+    function unflatten_to_Vector(v::Vector{T})
+        return convert(Vector{R}, v)
+    end
```
Comment (simsurace) [inline src/flatten.jl:37]:
```suggestion
    unflatten_to_Vector(v::Vector{T}) = convert(Vector{R}, v)
```

**Review by willtebbutt — APPROVED** [review]
Fantastic. Please feel free to merge once you've bumped the patch version. Thanks for fixing this

**Comment by simsurace** [comment]
Failures on Julia 1.5 are unrelated, see #62
